version: '3.8'

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "0.0.0.0:9000:9000"  # MinIO Console accessible externally
      - "0.0.0.0:9001:9001"  # MinIO API accessible externally

  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "0.0.0.0:27017:27017"  # MongoDB accessible externally

networks:
  default:
    name: minio-mongo-network